### ISSUE TITLE
Flask: Return json instead of html on error

### ISSUE THREAD

**Issue by 7erra** [MANVSim/MANVSim#104]
Currently Flask returns html documents when an error occurs. This should be changed so that json documents are returned with information about the error.

**Comment by YIllmann** [comment]
A certain KI tool told me:

"you can customize Flask’s error handling to return JSON instead of HTML. Here is an example of how you can do it:
```
from flask import Flask, jsonify

app = Flask(__name__)

@app.errorhandler(404)
def resource_not_found(e):
    return jsonify(error=str(e)), 404

@app.errorhandler(500)
def internal_server_error(e):
    return jsonify(error=str(e)), 500

# Add similar error handlers for other HTTP status codes
```
In this code, @app.errorhandler is a decorator that tells Flask to use the decorated function as the handler for a certain type of error. The function takes an exception instance as a parameter and returns a response that will be sent to the client.

You can add similar handlers for other HTTP status codes as needed. The jsonify function is used to convert the error message to a JSON response. Remember to return the appropriate HTTP status code along with the JSON response. This way, whenever an error occurs, Flask will call the appropriate error handler function and return a JSON response instead of an HTML page."

However it would be of interest if you can generalize it for a specific code range. In this case the KI says:

"Flask does not provide a built-in way to apply an error handler to a range of HTTP status codes. However, you can achieve this by creating a loop that registers an error handler for each status code in the range. Here’s an example:

```
from flask import Flask, jsonify

app = Flask(__name__)

def handle_error(e):
    return jsonify(error=str(e)), e.code

for code in range(400, 600):
    app.register_error_handler(code, handle_error)
```

In this code, the handle_error function is defined to return a JSON response containing the error message and HTTP status code. Then a loop is used to register this function as the error handler for each HTTP status code in the range from 400 to 599"
