### ISSUE TITLE
Web: Add OpenAPI specificiation to API calls made by the web frontend

### ISSUE THREAD

**Issue by 7erra** [MANVSim/MANVSim#117]

**Comment by H1ghBre4k3r** [comment]
@7erra does this ticket mean to create an OpenAPI specification for the web frontend?

**Comment by 7erra** [comment]
> @7erra does this ticket mean to create an OpenAPI specification for the web frontend?

Yes

**Comment by 7erra** [comment]
It might be worth it to check out [APIFlask](https://apiflask.com). It automatically generates API documentation, parses and validates requests and only returns json data. The migration seems simple enough as it is build on top of Flask. Thoughts @H1ghBre4k3r @YIllmann @simohlsen?

**Comment by simohlsen** [comment]
@7erra How does automatic API spec generation work in APIFlask? By app, by blueprint, or by path? We have three different APIs implemented in the server, so we need a way to differentiate.

Generally open to it, if short term benefits outweigh adoption overhead.

**Comment by H1ghBre4k3r** [comment]
It generates the spec across all registered endpoints. However, we currently do not really make use of it since we do not use the provided types and validation. Therefore, the documentation is quite sparse (see screenshot).

<img width="1436" alt="image" src="https://github.com/user-attachments/assets/0417b049-4cae-40d5-95ca-b1f951a394ec">
