### ISSUE TITLE
Web: Browser-specific logout after creating a new user or sending a message

### ISSUE THREAD

**Issue by lukas0820** [MANVSim/MANVSim#362]
During testing I noticed that users are logged out in the following scenarios while editing an execution:

 - When creating a new player
 - When sending a message

I have tested this across multiple browsers, and it is noteworthy that this behavior does not occur in every browser. Everything seems to work fine in Chrome (Windows), but I was logged out in Safari (macOS and iOS) and Firefox (Windows).

I tested this on the latest main branch (commit id:` 60813bbf73d931d1c4258a6b5ff876c40d6e6193`) using the` sadmin `user.

**Comment by lukas0820** [comment]
Firefox: There are no issues in the network analysis, but this error appears in the console:

```
gL https://batailley.informatik.uni-kiel.de:50003/assets/index-DNEbkihR.js:68
    Kv https://batailley.informatik.uni-kiel.de:50003/assets/index-DNEbkihR.js:38
    HE https://batailley.informatik.uni-kiel.de:50003/assets/index-DNEbkihR.js:40
    zE https://batailley.informatik.uni-kiel.de:50003/assets/index-DNEbkihR.js:40
    eO https://batailley.informatik.uni-kiel.de:50003/assets/index-DNEbkihR.js:40
    Yf https://batailley.informatik.uni-kiel.de:50003/assets/index-DNEbkihR.js:40
    $E https://batailley.informatik.uni-kiel.de:50003/assets/index-DNEbkihR.js:40
    I https://batailley.informatik.uni-kiel.de:50003/assets/index-DNEbkihR.js:25
    ie https://batailley.informatik.uni-kiel.de:50003/assets/index-DNEbkihR.js:25
```

**Comment by YIllmann** [comment]
Additionally, when editing a scenario the scenario reload action is returned with a Missing Auth header. Chrome does not have this problem. I would advise to switch to chrome for our presentation and declare the error as future work and bug

**Comment by YIllmann** [comment]
_Client Quickfix_: set Breakpoint in the newest Tracestep. Then the application works fine, without any issues. 
_Longterm fix_ might be to recheck the fetch methods. Due to the fix of the Debug Breakpoint the error seems to be a race condition in other browser than Chrome. The KI says:

1. Race Conditions: A race condition occurs when two or more asynchronous operations (like API requests or DOM updates) compete for the same resource, leading to unpredictable behavior. When you add a breakpoint, the timing changes, and this can "fix" the issue temporarily by giving enough time for one operation to complete before the next begins.
Solution: Add explicit waiting or control flow to ensure that asynchronous operations are completed in the right order. For example, ensure that the state is only updated after the API call completes successfully, and that no conflicting updates happen concurrently.
2. Re-renders or Component Unmounting: Sometimes, components can unmount or re-render unexpectedly while an asynchronous operation is in progress, leading to issues like trying to update state on an unmounted component. The breakpoint alters the timing, allowing the component to remain mounted long enough for the update to succeed.
Solution: Use a flag to track whether the component is still mounted before updating the state, as shown earlier. This avoids trying to update state on an unmounted component.
3. Debouncing/Throttling Issues: If you have multiple POST/PATCH requests firing in rapid succession, you might accidentally create conflicts or incomplete updates. By adding a breakpoint, you give the requests enough time to complete one at a time, so the problem seems to disappear.
Solution: Introduce debouncing or throttling to limit how frequently certain actions (e.g., API requests) are triggered.

**Comment by YIllmann** [comment]
I tested the features recently with Edge. No problems occured. It seem to be a Safari/Firefox issue.

**Comment by lukas0820** [comment]
The `action` function in React Router is meant to handle form submissions and other navigational actions. It runs outside the React component tree and doesn't have access to the browser's window object in all cases. I think a redirect is a better option here and solves the problem in my tests with firefox
